import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { KondateSolver } from "../components/KondateSolver";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>離乳食こんだて考える君</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>離乳食こんだて考える君</h1>
      <KondateSolver />
    </div>
  );
};

export default Home;
