import Head from "next/head";
import { KondateSolver } from "../components/KondateSolver";
import { DefaultFoods } from "../hooks/useFoods";

export const Kondatekun = (props: { defaultFoods?: DefaultFoods }) => {
  return (
    <div>
      <Head>
        <title>離乳食こんだて考える君</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>離乳食こんだて考える君</h1>
      <KondateSolver defaultFoods={props.defaultFoods} />
    </div>
  );
};
